[versions]
architectury-loom = "1.7-SNAPSHOT"
error_prone_annotations = "2.33.0"
fabric-loader = "0.16.7"
fabric-mc1182 = "0.77.0+1.18.2"
fabric-mc1192 = "0.77.0+1.19.2"
fabric-mc1194 = "0.87.2+1.19.4"
fabric-mc1201 = "0.92.2+1.20.1"
fabric-mc1202 = "0.91.6+1.20.2"
fabric-mc1204 = "0.97.2+1.20.4"
fabric-mc1206 = "0.100.8+1.20.6"
fabric-mc1211 = "0.105.0+1.21.1"
fabric-mc1212 = "0.105.4+1.21.2"
gson = "2.11.0"
jetbrains_annotations = "26.0.1"
ksyxis = "1.3.2"
lazydfu-mc1182 = "0.1.2"
lazydfu-mc1192 = "0.1.3"
minecraft-mc1182 = "1.18.2"
minecraft-mc1192 = "1.19.2"
minecraft-mc1194 = "1.19.4"
minecraft-mc1201 = "1.20.1"
minecraft-mc1202 = "1.20.2"
minecraft-mc1204 = "1.20.4"
minecraft-mc1206 = "1.20.6"
minecraft-mc1211 = "1.21.1"
minecraft-mc1212 = "1.21.2-pre3"
modmenu-mc1182 = "3.2.5"
modmenu-mc1192 = "4.1.2"
modmenu-mc1194 = "6.3.1"
modmenu-mc1201 = "7.2.2"
modmenu-mc1202 = "8.0.1"
modmenu-mc1204 = "9.2.0"
modmenu-mc1206 = "10.0.0"
modmenu-mc1211 = "11.0.3"
modmenu-mc1212 = "12.0.0-beta.1"
slf4j = "2.0.16"

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }

[libraries]
error_prone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error_prone_annotations" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-mc1182 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1182" }
fabric-mc1192 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1192" }
fabric-mc1194 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1194" }
fabric-mc1201 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1201" }
fabric-mc1202 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1202" }
fabric-mc1204 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1204" }
fabric-mc1206 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1206" }
fabric-mc1211 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1211" }
fabric-mc1212 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1212" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
ksyxis = { module = "maven.modrinth:ksyxis", version.ref = "ksyxis" }
lazydfu-mc1182 = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu-mc1182" }
lazydfu-mc1192 = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu-mc1192" }
minecraft-mc1182 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1182" }
minecraft-mc1192 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1192" }
minecraft-mc1194 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1194" }
minecraft-mc1201 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1201" }
minecraft-mc1202 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1202" }
minecraft-mc1204 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1204" }
minecraft-mc1206 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1206" }
minecraft-mc1211 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1211" }
minecraft-mc1212 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1212" }
modmenu-mc1182 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1182" }
modmenu-mc1192 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1192" }
modmenu-mc1194 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1194" }
modmenu-mc1201 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1201" }
modmenu-mc1202 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1202" }
modmenu-mc1204 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1204" }
modmenu-mc1206 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1206" }
modmenu-mc1211 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1211" }
modmenu-mc1212 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1212" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
