[versions]
architectury-loom = "1.7-SNAPSHOT"
enablemultiplayermode = "1.0.0+Fabric1.16.X"
error_prone_annotations = "2.34.0"
fabric-loader = "0.16.7"
fabric-mc1165 = "0.42.0+1.16"
fabric-mc1171 = "0.46.1+1.17"
fabric-mc1182 = "0.77.0+1.18.2"
fabric-mc1192 = "0.77.0+1.19.2"
fabric-mc1194 = "0.87.2+1.19.4"
fabric-mc1201 = "0.92.2+1.20.1"
fabric-mc1202 = "0.91.6+1.20.2"
fabric-mc1204 = "0.97.2+1.20.4"
fabric-mc1206 = "0.100.8+1.20.6"
fabric-mc1211 = "0.106.0+1.21.1"
fabric-mc1212 = "0.106.1+1.21.2"
gson = "2.11.0"
jetbrains_annotations = "26.0.1"
ksyxis = "1.3.2"
log4j = "2.24.1"
lazydfu-old = "0.1.2"
lazydfu-new = "0.1.3"
minecraft-mc1165 = "1.16.5"
minecraft-mc1171 = "1.17.1"
minecraft-mc1182 = "1.18.2"
minecraft-mc1192 = "1.19.2"
minecraft-mc1194 = "1.19.4"
minecraft-mc1201 = "1.20.1"
minecraft-mc1202 = "1.20.2"
minecraft-mc1204 = "1.20.4"
minecraft-mc1206 = "1.20.6"
minecraft-mc1211 = "1.21.1"
minecraft-mc1212 = "1.21.2-rc1"
modmenu-mc1165 = "1.16.23"
modmenu-mc1171 = "2.0.17"
modmenu-mc1182 = "3.2.5"
modmenu-mc1192 = "4.1.2"
modmenu-mc1194 = "6.3.1"
modmenu-mc1201 = "7.2.2"
modmenu-mc1202 = "8.0.1"
modmenu-mc1204 = "9.2.0"
modmenu-mc1206 = "10.0.0"
modmenu-mc1211 = "11.0.3"
modmenu-mc1212 = "12.0.0-beta.1"

[plugins]
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }

[libraries]
enablemultiplayermode = { module = "maven.modrinth:enablemultiplayermode", version.ref = "enablemultiplayermode" }
error_prone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error_prone_annotations" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-mc1165 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1165" }
fabric-mc1171 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1171" }
fabric-mc1182 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1182" }
fabric-mc1192 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1192" }
fabric-mc1194 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1194" }
fabric-mc1201 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1201" }
fabric-mc1202 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1202" }
fabric-mc1204 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1204" }
fabric-mc1206 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1206" }
fabric-mc1211 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1211" }
fabric-mc1212 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-mc1212" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
ksyxis = { module = "maven.modrinth:ksyxis", version.ref = "ksyxis" }
log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
lazydfu-old = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu-old" }
lazydfu-new = { module = "maven.modrinth:lazydfu", version.ref = "lazydfu-new" }
minecraft-mc1165 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1165" }
minecraft-mc1171 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1171" }
minecraft-mc1182 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1182" }
minecraft-mc1192 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1192" }
minecraft-mc1194 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1194" }
minecraft-mc1201 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1201" }
minecraft-mc1202 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1202" }
minecraft-mc1204 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1204" }
minecraft-mc1206 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1206" }
minecraft-mc1211 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1211" }
minecraft-mc1212 = { module = "com.mojang:minecraft", version.ref = "minecraft-mc1212" }
modmenu-mc1165 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1165" }
modmenu-mc1171 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1171" }
modmenu-mc1182 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1182" }
modmenu-mc1192 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1192" }
modmenu-mc1194 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1194" }
modmenu-mc1201 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1201" }
modmenu-mc1202 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1202" }
modmenu-mc1204 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1204" }
modmenu-mc1206 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1206" }
modmenu-mc1211 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1211" }
modmenu-mc1212 = { module = "com.terraformersmc:modmenu", version.ref = "modmenu-mc1212" }
